### ISSUE TITLE
Set and update default data in remote document for multiplayer editing

### ISSUE THREAD

**Issue by lerrybe** [lerrybe/collab-dotting#2]
### Notes
The current application is trying to implement features to support multiplayer editing using a library [dotting](https://github.com/hunkim98/dotting) created based on canvas tags. To enable multiple users to collaborate seamlessly, the following features must be implemented:

1. Update remote document (type: `DotingDoc`) with concurrent changes:
> Implement a mechanism to update the pixel information performed by the client.
Use `update` function of `yorkie-js-sdk` to propagate changes to remote document. 

2. Synchronize data through subscription:
> When the remote document is modified, the data received during subscription is applied to the data in the current client.

If we resolve these issues, we're ready to start efficient, simultaneous editing in a multiplayer environment. Multiple users can collaborate on the same canvas to view changes made by others in real time and experience a seamless, synchronized editing experience. The example dataType you need looks like below.

```typescript
import { JSONArray, JSONObject } from 'yorkie-js-sdk';
import { ColorChangeItem, PixelModifyItem } from 'dotting';

// default dataType to start
export type DottingDoc = {
  indices: JSONObject<Indices>;
  strokedPixels: JSONArray<ColorChangeItem>;
  data: YorkieData;
};

export type Indices = {
  topRowIndex: number;
  bottomRowIndex: number;
  leftColumnIndex: number;
  rightColumnIndex: number;
};

export type YorkieData = Record<number, Record<number, PixelModifyItem>>;
```

---

Yorkie provides a library for multiplayer editing. Basically, the CRDT structure is used. Details are shown in docs below, and it would be good to start development by referring to them.

🔗 Docs: https://yorkie.dev/docs/getting-started/with-js-sdk
🔗 examples: https://github.com/yorkie-team/yorkie-js-sdk/tree/main/examples

**Comment by hunkim98** [comment]
Great job! Your approach is correct! Keep up the good work!
